name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline.yml
    with:
      doRelease: true
